name: deploy gh pages

env:
  CI: true

on:
  push:
    branches: [ master ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      
      
      - name: deploy with gh-pages
        uses: actions/setup-node@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
          USERMAIL: ${{ secrets.USER_EMAIL }}
      
      - run: npm ci
      - run: |
          git remote set-url origin https://git:${secrets.GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.name "Anyul Rivas"
          git config --global user.email "support+actions@github.com"
          npm run deploy
